### ISSUE TITLE
Settings are not always properly retrieved

### ISSUE THREAD

**Issue by agarny** [opencor/webapp#2]
Say that you move the app window to the top left corner of the screen then its `mainWindowState.x` will be equal to `0`. However, when restarting the app, `mainWindowState.x` will be equal to `295` (on macOS)! This is because we have `x: settings.getSync('mainWindowState.x') || horizontalSpace` while we should have `x: x !== undefined && x !== null ? x : horizontalSpace` with `x = settings.getSync('mainWindowState.x')`.

**Comment by dbrnz** [comment]
Hmm, `settings.getSync('mainWindowState.x') || horizontalSpace` should be sufficient.

Testing in node's CLI:
```
> t = null
null
> x = t || 1
1
> x
1
> t = undefined
undefined
> x = t || 1
1
> x
1
```

**Comment by agarny** [comment]
> Hmm, `settings.getSync('mainWindowState.x') || horizontalSpace` should be sufficient.

Well, the issue is not so much with `t = undefined` or `t = null` but with `t = 0`:
```node
> t = 0
0
> x = t || 1
1
> x
1
```
The value of `x` is obviously correct, but I was after was actually for `x` to be equal to `0`. So, in this particular case, I needed to tests against `undefined`, but I ended up also testing against `null` because of TypeScript complaining about `t` being maybe equal to `null`.

Anyway, it's all working fine now by having:
```typescript
const x = settings.getSync('mainWindowState.x')
...
x: x !== undefined && x !== null ? x : horizontalSpace
```

**Comment by agarny** [comment]
Closing as a result of PR #3.

**Comment by dbrnz** [comment]
Aha, I've also been caught by that one... (`0` being `false`).
